name: pia_m3_1
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.0.0
  - torchvision
  - torchaudio
##  - pytorch-cuda=11.7
  - pip
  - pip:
    - diffusers
    - transformers==4.38.1
    - xformers==0.0.16
    - imageio==2.27.0
    ##- decord==0.6.0
    - eva-decord
    - gdown
    - accelerate==0.27.2
    - stable_diffusion_videos
    - einops
    - omegaconf
    - safetensors
    - imageio-ffmpeg==0.4.9
    - gradio
    - wandb
